[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2461451f012de70a8c5c47b2053a72b3338fcb70"
os = "macos"

    [[GMP.download]]
    sha256 = "7787c86ac9aece2c7da4f821b56c284486c6540570a553a45890b459957ecb42"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "6355b85fdaa7a7e3613b52e4f0a6b10eb85c2b98"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "5fb1eed4b56105b9b1234e5edd4f168a920aad30f5edbdadfe5ade7292c73182"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2107026ffb18062ec007e24c293df5c169b1d8b4"
os = "freebsd"

    [[GMP.download]]
    sha256 = "7dd8aafd5846e4e213ff75c7904310e4b66e832c9be0e40610a3e8537f9dc80e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "fcfc864a2e20cb73a33d104aee64cccca7777ec9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c6be2dbe4f9d646bae8e9cce65754c042e97b5de9a0e7bab266370a11af3b2c8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "1b592174c598169c2e478d1544a265b6c155a138"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f1dcca178f556526df4d0cc3e860f9519d618986dcd9ec0940f7e4b7a69e8f78"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "8e47356717edb1ff37cef9493db4bb706527d3fd"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c46d28324174945d17eb361be78a207fff04d6dea0f8dc544af88b5ae7d5e6b9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "50649f2a1e14f2a2c2f5a995e64321acb1dba7f3"
os = "windows"

    [[GMP.download]]
    sha256 = "4fd82486c2dabab279df94050440bba66c2ba6a3bbf431ac56bf23dcccaffe3a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "92c243ff1e700ac63ff37ae435fb14a304e81947"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "6cf7e572a4bba747c658394e13186f9b4265060822c92838a17c874ff394217c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "5865dc3a5d6f4dd804a48c1ea6dc2d2e6e0ec951"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "47a1d03b44a00613175431fe7495c411d0fed54154628bc6ab3a08284b40f325"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "ad857524bfea6b48edf0615015ce13a4e0977bbc"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ba02af7ae3fa259a43a724d2b46139d9d8eb06a384e0fff1021bd06c7e14f9a3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "646e15e8de2e7f4dc1291ba6d8953ea0d6e4d3ee"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7bd0149ed2827778b226bb0122e6ad6c93d77c90ddf2722eb7a6c965abb5f4e0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "7d418e5e98764349d7ffdf6a3628f769936ee4bb"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "70ffec859afe0d8a17dced1dd3ed62a34329e2e5e297bb954c0d7d380fd2dac4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "a0d4e16d7de91e2459e74f9bdf39ebb8fb872a62"
os = "windows"

    [[GMP.download]]
    sha256 = "55d184b8dd867919f229931a58ac7482b8615c841f85515012a1e8662dcae9e3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+3/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
