[[GMP]]
arch = "x86_64"
git-tree-sha1 = "e0ccbe2db38c94ebfe49d44460a861a902c9dc00"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a9f888eadfeec8faa60741656e7e35e942ada497edcacaac4a3d7916fe9dcaa6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "81f078567e51132a526f5bc44ec8e740837d9777"
os = "macos"

    [[GMP.download]]
    sha256 = "b0a4be941b55bb4a526cce91ccb65021475fc0a2ae22ae8807a06205fc4ed240"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "bb6293c3c69ae07471f0bdbae4c3969438505f5b"
os = "windows"

    [[GMP.download]]
    sha256 = "92ce3c6fda5339d61e9a845c2ae8e1f0168411ceb5b61e5b1b1cdbbbda70783c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "6e56065f045bacba100d537c1f1b88881b33dab6"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "65803b63e8974f7000e056811c1ac0bab845e040535f24c18b4803140d8444bc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "11656ae876ff3362f9cdd2940be2287b5d6e5618"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "0d0b43e19e753e4b901330d2ffe7f6df5ef5f70e008d8c94130dd16e4b2db106"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "a3864538e32f689d44281c344f7c0ba98ba45897"
os = "windows"

    [[GMP.download]]
    sha256 = "bc1c981b6cb77b3e70ff087fa8b607f7f8cfd33112e78feb4eef972002066acb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "1c4eb88ed57dcac18fc9dd616d15e05d4ada131f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "403209ad252456ebbc3ca7332678b23326c44ade09e613b78524698445c28557"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "6fa6456acb9812302d6c2c56c05a27471593a9ae"
os = "freebsd"

    [[GMP.download]]
    sha256 = "8897470b206325cbfcb758eb944d4010919918b2684e02afc52abb1bd95e9e72"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "7c96c34cafa13ceed2c3d72b1db0a9eb88157cfa"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "4361e3badbc60128f66eb6aa7bfda8a1af060a28932cb18fa0ae395d6f659465"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "78d1c0ef00411cf6990c1f7e4f7330ba26f6f302"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "2b3ddc21c9ce60d45cdee0bcfabd8b80da459c3b2c99dec8e3d0cb72f0e7ebcb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "785458ac9d2b1c77f6da2cf2ee3cd51f34f9d4f3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d274443142fbcb84f6084ae99d95352612703fab305e75ce9400001c3f176f85"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "0d28447d135bb3c2d195d8545e7525e81f93ac04"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d278e20dca8c666acaecdc4bf26d613401feab1c1b69ff3787383cf439d574f6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "a601192e2449779259079f0cf1f509626787cd2d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eed989b515804a62a0d03c05e68456ae860584c9eb999e300c1c64ecc1194369"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+2/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
